//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DiesteinMDEppc.rc
//
#define IDCANCEL2                       3
#define IDNEU                           3
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_AUSWAHL              129
#define IDD_DIALOG_INFO                 131
#define IDD_DIALOG_EIGENSCHAFTEN        132
#define IDD_DIALOG_SAVEMSG              133
#define IDD_DIALOG_PREISE               134
#define IDD_DIALOG_LAGERUM              135
#define IDD_DIALOG_OBERFLAENDERN        136
#define IDD_DIALOG_OBERFLBUCH           137
#define IDD_DIALOG_POSINFO              138
#define IDD_DIALOG_PLATTENZUGANG        139
#define IDD_DIALOG_AUFTRAGSBEARB        140
#define IDD_DIALOG_POSITIONEN           141
#define IDD_DIALOG_BESTELLEINGANG       144
#define IDD_DIALOG_BESTELLBUCH          145
#define IDD_DIALOG_EINKAUF              146
#define IDD_DIALOG_RUECKZUGANG          147
#define IDD_DIALOG1                     148
#define IDD_DIALOG_PREISEVERANK         148
#define IDD_DIALOG_VERANKSTKL           149
#define IDD_DIALOG_BENUTZER             150
#define IDD_DIALOG_STEINBRUCH           151
#define IDD_DIALOG_STEINBRUCHENTRY      152
#define IDD_DIALOG_STEINBRUCHEMAIL      152
#define IDD_DIALOG_GATTERN              155
#define IDD_DIALOG_GATTERAUFTRAEGE      156
#define IDD_DIALOG_GATTER_NEU           158
#define IDD_DIALOG_GATTERAUSWAHL        159
#define IDD_DIALOG_GATTEROFFENEAUFTRAEGE 160
#define IDD_DIALOG_GATTERPLATTEN        161
#define IDD_DIALOG_GATTERDATEN          162
#define IDD_DIALOG_GATTERSTANDFUGE      163
#define IDD_DIALOG2                     164
#define IDD_DIALOG_BLOCKVORABINFO       164
#define IDD_DIALOG_SCHNITTEJEBLOCK      165
#define IDD_DIALOG_BL                   166
#define IDD_DIALOG_BLOCKDATEN           166
#define IDC_COMBO_STEINNUMMER           1000
#define IDC_COMBO_LAGER_NEU             1001
#define IDC_EDIT_MENGE1                 1001
#define IDC_COMBO_FEHLER                1001
#define IDC_EDIT_REST                   1002
#define IDC_STATIC_FEHLER               1002
#define IDC_COMBO_BISSTEINNUMMER        1002
#define IDC_COMBO_FEHLER1               1003
#define IDC_LIST1                       1005
#define IDC_LIST_SAETZE                 1005
#define IDC_EDIT_LAENGE                 1006
#define IDC_STATIC_VERANKERUNG          1006
#define IDC_EDIT_BREITE                 1007
#define IDC_STATIC_SAETZE               1007
#define IDC_EDIT_DICKE                  1008
#define IDC_EDIT_PASSWORT               1008
#define IDC_COMBO_NAME                  1009
#define IDC_EDIT_LAENGENETTO            1009
#define IDC_EDIT_GEWICH                 1009
#define IDC_EDIT_NETTOLAENGE            1009
#define IDC_STATIC_NAME                 1010
#define IDC_EDIT_BREITENETTO            1010
#define IDC_EDIT_NETTOBREITE2           1010
#define IDC_EDIT_NETTOBREITE            1010
#define IDC_EDIT_FEHLLAENGE             1011
#define IDC_STATIC_PASSWORT             1011
#define IDC_EDIT_DICKENETTO             1011
#define IDC_STATIC_ANMELDUNG            1012
#define IDC_EDIT_NETTODICKE             1012
#define IDC_EDIT_FEHLBREITE             1014
#define IDC_COMBO_MATERIAL              1014
#define IDC_EDIT_FEHLNUMMER             1015
#define IDC_EDIT_NUMMER                 1015
#define IDC_STATIC_MASSEBRUTTO          1016
#define IDC_STATIC_STEINNUMMER          1017
#define IDC_STATIC_MASSENETTO           1017
#define IDC_STATIC_MENGE1               1018
#define IDC_STATIC_POSITIONEN1          1018
#define IDC_STATIC_RESERVIERT1          1018
#define IDC_BUTTON_UEBERSICHT           1018
#define IDC_STATIC_BISSTEINNUMMER       1018
#define IDC_STATIC_MENGE2               1019
#define IDC_EDIT_SCHICHT                1019
#define IDC_STATIC_ARTIKEL              1020
#define IDC_BUTTON_BACK                 1020
#define IDC_EDIT_GEWICHT                1020
#define IDC_STATIC_MATERIAL             1021
#define IDC_STATIC_OBERFLAECHE          1022
#define IDC_STATIC_NUMMER               1022
#define IDC_STATIC_LAENGE               1023
#define IDC_STATIC_BREITE               1024
#define IDC_STATIC_DICKE                1025
#define IDC_STATIC_FEHLLAENGE           1026
#define IDC_STATIC_PREIS1               1026
#define IDC_STATIC_GALBD                1026
#define IDC_STATIC_HINWEIS1             1026
#define IDC_STATIC_SCHICHT              1026
#define IDC_STATIC_FEHLNUMMER           1027
#define IDC_STATIC_PREIS2               1027
#define IDC_STATIC_HINWEIS2             1027
#define IDC_STATIC_BLAETTERN            1027
#define IDC_STATIC_FEHLBREITE           1028
#define IDC_STATIC_PREIS3               1028
#define IDC_BUTTON_NEXT                 1028
#define IDC_STATIC_GEWICHT              1028
#define IDC_STATIC_FEHLECKE             1029
#define IDC_STATIC_PREIS4               1029
#define IDC_BUTTON_LOESCHEN             1029
#define IDC_STATIC_STEINSAETZE          1030
#define IDC_STATIC_ARTIKELNUMMER        1030
#define IDC_STATIC_MASSE                1030
#define IDC_BUTTON_NEU                  1030
#define IDC_STATIC_RESERVIERT           1031
#define IDC_STATIC_ME1                  1031
#define IDC_COMBO_GRUPPE                1031
#define IDC_STATIC_GEWICH               1031
#define IDC_STATIC_MASSE2               1031
#define IDC_STATIC_MENGE1V              1032
#define IDC_STATIC_ME2                  1032
#define IDC_STATIC_GRUPPE               1032
#define IDC_STATIC_GEWI                 1032
#define IDC_STATIC_NETTOMASSE           1032
#define IDC_STATIC_MENGE2V              1033
#define IDC_STATIC_ARTIKEL_TEXT         1033
#define IDC_COMBO_AUFTRAEGE             1033
#define IDC_EDIT_LAENGEBRUTTO           1033
#define IDC_STATIC_GEWI2                1033
#define IDC_STATIC_GEWITEXT             1033
#define IDC_STATIC_ARTIKEL_TX           1034
#define IDC_STATIC_MATERIAL_TEXT        1034
#define IDC_LIST_POSITIONEN             1034
#define IDC_EDIT_BREITEBRUTTO           1034
#define IDC_STATIC_HINWEIS              1035
#define IDC_STATIC_OBERFLAECHE_TEXT     1035
#define IDC_BUTTON_BEARBEITEN           1035
#define IDC_STATIC_GAMATERIALTEXT       1035
#define IDC_LIST_RESTBLOCK              1035
#define IDC_STATIC_HINWEIS_TX           1036
#define IDC_STATIC_DICKE_TEXT           1036
#define IDC_STATIC_AUFTRAEGE            1036
#define IDC_EDIT_DICKEBRUTTO            1036
#define IDC_STATIC_MATERIAL_TX          1037
#define IDC_STATIC_LAENGE_TEXT          1037
#define IDC_BUTTON_LOESCHAUFTRAG        1037
#define IDC_STATIC_HINWEIS2_TEXT        1037
#define IDC_BUTTON_BLOCKERFASSUNG       1037
#define IDC_BUTTON_EMAIL                1037
#define IDC_STATIC_OBERFLAECHE_TX       1038
#define IDC_STATIC_BREITE_TEXT          1038
#define IDC_STATIC_POSITIONEN           1038
#define IDC_COMBO_RECEPIENT             1038
#define IDC_STATIC_RES                  1039
#define IDC_STATIC_LAENGE_TX            1039
#define IDC_STATIC_ME1V                 1039
#define IDC_STATIC_LOESCHAUFTRAG        1039
#define IDC_STATIC_RECEPIENT            1039
#define IDC_STATIC_BREITE_TX            1040
#define IDC_STATIC_ME2V                 1040
#define IDC_BUTTON_ADDAUFTRAG           1040
#define IDC_STATIC_GALAENGETEXT         1040
#define IDC_BUTTON_SEND                 1040
#define IDC_STATIC_DICKE_TX             1041
#define IDC_BUTTON_LOESCHPOSITION       1041
#define IDC_BUTTON_POSHINZU             1041
#define IDC_STATIC_GABREITETEXT         1041
#define IDC_STATIC_HINWEIS1_TEXT        1041
#define IDC_EDIT1                       1041
#define IDC_EDIT_BETREFF                1041
#define IDC_EDIT_LAENGE_ALT             1041
#define IDC_EDIT_LADUNG                 1041
#define IDC_EDIT_DATUMANFANG            1041
#define IDC_EDIT_KOSTEN                 1041
#define IDC_STATIC_PREIS1_TX            1042
#define IDC_STATIC_LOESCHPOSITION       1042
#define IDC_STATIC_AUFTRAGSNAME         1042
#define IDC_STATIC_GADICKETEXT          1042
#define IDC_STATIC_BETREFF              1042
#define IDC_EDIT_BREITE_ALT             1042
#define IDC_BUTTON_LOESCHPOSITION2      1042
#define IDC_EDIT_LIEFBLOCKNR            1042
#define IDC_STATIC_PREIS2_TX            1043
#define IDC_STATIC_POSITIONENZAHL       1043
#define IDC_EDIT2                       1043
#define IDC_EDIT_TEXT                   1043
#define IDC_EDIT_DICKE_ALT              1043
#define IDC_STATIC_LOESCHPOSITION2      1043
#define IDC_EDIT_DATUMENDE              1043
#define IDC_BUTTON_LOESCHRESTBLOCK      1043
#define IDC_EDIT_LAENGE_NEU2            1043
#define IDC_EDIT_LAGERORT               1043
#define IDC_STATIC_PREIS3_TX            1044
#define IDC_EDIT_BUCHMENGE              1044
#define IDC_COMBO2                      1044
#define IDC_COMBO_SICHERUNG             1044
#define IDC_EDIT_LAENGE_NEU             1044
#define IDC_COMBO_LIEFERAN              1044
#define IDC_STATIC_LOESCHRESTBLOCK      1044
#define IDC_EDIT_BREITE_NEU2            1044
#define IDC_STATIC_PREIS4_TX            1045
#define IDC_BUTTON_POSANZEIGEN          1045
#define IDC_BUTTON_SENDSICH             1045
#define IDC_EDIT_BREITE_NEU             1045
#define IDC_EDIT_POSLAGERORT            1045
#define IDC_BUTTON_INVENTUR             1046
#define IDC_STATIC_ARTIKELNUMMER_TX     1046
#define IDC_LIST_POSINFO                1046
#define IDC_STATIC_SICHERUNG            1046
#define IDC_EDIT_DICKE_NEU              1046
#define IDC_BUTTON_BLOCKANZEIGEN        1046
#define IDC_BUTTON_ZUGANG               1047
#define IDC_STATIC_LAGER_TX             1047
#define IDC_CHECK_RUECK                 1047
#define IDC_BUTTON1                     1047
#define IDC_BUTTON_AENDERN              1047
#define IDC_BUTTON_SPEICHERN            1047
#define IDC_BUTTON_VORABINFO            1047
#define IDC_BUTTON_ABBRUCH              1047
#define IDC_BUTTON_BESTELLEINGANG       1048
#define IDC_STATIC_RESJANEIN            1048
#define IDC_CHECK_ENDE                  1048
#define IDC_STATIC_DATEINAME            1048
#define IDC_CHECK_REST                  1048
#define IDC_BUTTON_OBERFLAENDERN        1049
#define IDC_STATIC_BLOCKZAHL            1049
#define IDC_BUTTON_STEINBRUCH           1050
#define IDC_SPIN_NUMBER                 1050
#define IDC_STATIC_EMAIL                1051
#define IDC_BUTTON_TEST                 1051
#define IDC_BUTTON_MASSEAENDERN         1051
#define IDC_COMBO_ME1                   1052
#define IDC_COMBO_STEINNR               1052
#define IDC_BUTTON_GATTERN              1052
#define IDC_COMBO_ME2                   1053
#define IDC_STATIC_NEU                  1053
#define IDC_BUTTON_PLATTENZUGANG        1053
#define IDC_STATIC_ALT                  1054
#define IDC_STATIC_ALT2                 1055
#define IDC_STATIC_BLOCKZAHL2           1056
#define IDC_STATIC_NEU2                 1056
#define IDC_EDIT_LAGERORT_ALT           1058
#define IDC_EDIT_BESTELLNR              1059
#define IDC_COMBO_LAGERORT_NEU          1059
#define IDC_EDIT_BESTELLPOS             1060
#define IDC_EDIT_STEINNR                1061
#define IDC_COMBO_GATTER                1061
#define IDC_STATIC_ARTIKELGRUPPE        1062
#define IDC_EDIT_STEINNRALT             1062
#define IDC_STATIC_LADUNG               1062
#define IDC_COMBO_BLOECKE               1062
#define IDC_BUTTON_HINZU                1063
#define IDC_COMBO1                      1063
#define IDC_COMBO_SCHNITTFLAECHE        1063
#define IDC_STATIC_MATERIALART          1064
#define IDC_EDIT_HINWEIS                1065
#define IDC_STATIC_GATTER               1065
#define IDC_BUTTON_EIGENSCHAFTEN        1066
#define IDC_STATIC_GATTERLADUNG         1066
#define IDC_STATIC_LAGERORT             1067
#define IDC_COMBO_ARTIKELGRUPPE         1067
#define IDC_STATIC_BLOECKE              1067
#define IDC_BUTTON_INFOVORABDATEN       1067
#define IDC_STATIC_LIEFERANT            1068
#define IDC_COMBO_MATERIALGRUPPE        1068
#define IDC_STATIC_ARTIKEL2             1068
#define IDC_STATIC_PLATTEN              1068
#define IDC_STATIC_LAGERORT_TX          1069
#define IDC_COMBO_MATERIALART           1069
#define IDC_EDIT_PREIS                  1069
#define IDC_BUTTON_PLATTEN              1069
#define IDC_STATIC_LIEFERANT_TX         1070
#define IDC_COMBO_OBERFLAECHE           1070
#define IDC_BUTTON_GATTERDATEN          1070
#define IDC_EDIT_STEINNR_bIS            1070
#define IDC_EDIT_STEINNRBIS             1070
#define IDC_COMBO_LAGERORT              1071
#define IDC_STATIC_BLOCKNUMMER          1071
#define IDC_BUTTON_PLATTEN2             1071
#define IDC_BUTTON_STANDFUGE            1071
#define IDC_COMBO_LIEFERANT             1072
#define IDC_COMBO_ARTIKELGR             1072
#define IDC_EDIT_MENGE                  1072
#define IDC_BUTTON_RESTBLOECKE          1072
#define IDC_EDIT_ZEITANFANG             1073
#define IDC_BUTTON_INFO                 1074
#define IDC_EDIT_ZEITENDE               1074
#define IDC_BUTTON_VERKAUF              1075
#define IDC_STATIC_LAGER_ALT            1075
#define IDC_EDIT_ZAEHLERANFANG          1075
#define IDC_BUTTON_PRODUKTION           1076
#define IDC_STATIC_LAGER_NEU            1076
#define IDC_EDIT_ZAEHLERENDE            1076
#define IDC_BUTTON_EINKAUF              1077
#define IDC_EDIT_LAGER_ALT              1077
#define IDC_EDIT_SANDVERBRAUCH          1077
#define IDC_BUTTON_LAGERUM              1078
#define IDC_STATIC_MENGE                1078
#define IDC_EDIT_BLOCKHOEHE             1078
#define IDC_BUTTON_PREISINFO            1079
#define IDC_STATIC_VERFUEGBAR           1079
#define IDC_COMBO_LAGER                 1079
#define IDC_STATIC_BESTNR               1079
#define IDC_COMBO_BESTELLNR             1079
#define IDC_EDIT_BLATTART               1079
#define IDC_BUTTON_LIEFERUNG            1080
#define IDC_STATIC_BESTPOS              1080
#define IDC_STATIC_ME                   1080
#define IDC_CHECK_NEUEBLAETTER          1080
#define IDC_BUTTON_RESERVIERUNG         1081
#define IDC_STATIC_BESTNRTEXT           1081
#define IDC_EDIT_ANZSCHNITTE            1081
#define IDC_STATIC_BESTPOSTEXT          1082
#define IDC_STATIC_ANFANG               1082
#define IDC_STATIC_ARTIKELTEXT          1083
#define IDC_STATIC_ENDE                 1083
#define IDC_STATIC_CONTAINER            1084
#define IDC_STATIC_SANDVERBRAUCH        1084
#define IDC_STATIC_CONTAINERTEXT        1085
#define IDC_STATIC_OBERFLTEXT           1085
#define IDC_STATIC_SAECKE               1085
#define IDC_STATIC_BESTELLNR            1086
#define IDC_STATIC_GAARTIKELTEXT        1086
#define IDC_STATIC_LAGERTEXT            1086
#define IDC_STATIC_BLATTART             1086
#define IDC_STATIC_POSINFO              1087
#define IDC_STATIC_ANZSCHNITTE          1087
#define IDC_EDIT_SANDVERBRAUCH2         1088
#define IDC_EDIT_KALKVERBRAUCH          1088
#define IDC_STATIC_SCHNITTFLAECHE       1088
#define IDC_STATIC_LAGER                1089
#define IDC_STATIC_ZEIT                 1089
#define IDC_EDIT_LIEFERSCHEIN           1090
#define IDC_STATIC_SET                  1090
#define IDC_STATIC_ZAEHLERSTAND         1090
#define IDC_EDIT_DATUM                  1091
#define IDC_BUTTON2                     1091
#define IDC_BUTTON_UEBERNEHMEN          1091
#define IDC_BUTTON_JEBLOCK              1091
#define IDC_BUTTON_BLOCKMASSE           1091
#define IDC_STATIC_LIEFERSCHEIN         1092
#define IDC_STATIC_RESTBLOCK            1092
#define IDC_STATIC_DATUM                1093
#define IDC_CHECK_STANDFUGE             1093
#define IDC_STATIC_POSITION             1094
#define IDC_STATIC_KOSTEN               1094
#define IDC_CHECK_TEILUNG               1094
#define IDC_STATIC_STEINNR              1095
#define IDC_STATIC_LIEFBLOCKNR          1095
#define IDC_STATIC_PREIS                1096
#define IDC_STATIC_STEINNRALT           1096
#define IDC_STATIC_SAND                 1096
#define IDC_STATIC_DIESTEINMDE          1097
#define IDC_STATIC_TITELTEXT            1097
#define IDC_STATIC_KALK                 1097
#define IDC_STATIC_MOBILEDE             1098
#define IDC_STATIC_BLOck                1098
#define IDC_STATIC_MATERIALGRUPPE       1099
#define IDC_BUTTON_ABBRECHEN            1099
#define IDC_STATIC_LAGERORT_E           1100
#define IDC_BUTTON_ABBRECHEN2           1100
#define IDC_STATIC_LAGERDATUM           1100
#define IDC_STATIC_TEXTFELD             1101
#define IDC_STATIC_BRUTTOMASSE          1101
#define IDC_STATIC_LIEFERANT_E          1102
#define IDC_BUTTON_ANFANG               1104
#define IDC_BUTTON_ENDE                 1105
#define IDC_EDIT_LIEFERSCHEINDATUM      1105
#define IDC_STATIC_LIEFERSCHEINDATUM    1106
#define IDC_STATIC_LAGERUMBUCHUNG       1107
#define IDC_CHECK1                      1107
#define IDC_BUTTON_SET                  1108
#define IDC_BUTTON_BUCHUNGEN            1108
#define IDC_BUTTON_ERASE                1108
#define IDC_BUTTON_VORHER               1108
#define IDC_STATIC_SATZNUMMER           1109
#define IDC_EDIT_FEHLLAENGE_ALT         1109
#define IDC_COMBO_SATZNUMMERN           1110
#define IDC_EDIT_FEHLBREITE_ALT         1110
#define IDC_BUTTON_EINZEL               1111
#define IDC_EDIT_FEHLLAENGE_NEU2        1111
#define IDC_EDIT_TEXTFELD               1112
#define IDC_EDIT_FEHLBREITE_NEU2        1112
#define IDC_STATIC_MASSE3               1113
#define IDC_BUTTON_NAECHSTER            1114
#define IDC_STATIC_BRUTTO               1115
#define IDC_STATIC_NETTO                1116
#define IDC_STATIC_BIS                  1117
#define IDC_STATIC_OBERFL_ALT           1118
#define IDC_BUTTON3                     1118
#define IDC_BUTTON_SUMME                1118
#define IDC_STATIC_OBERFL_NEU           1119
#define IDC_EDIT_OBERFL_ALT             1120
#define IDC_COMBO_OBERFL_NEU            1121
#define IDC_COMBO_STEINNUMMERN          1122
#define IDC_EDIT_FEHLER_ALT             1123
#define IDC_LIST_OBERFL                 1124
#define IDC_COMBO_FEHLER_NEU            1124
#define IDC_BUTTON_UNDO                 1125
#define IDC_STATIC_TEXT                 1126
#define IDC_BUTTON_AUTO                 1126
#define IDC_STATIC_BUCHUNGEN            1127
#define IDC_STATIC_MASSE_ALT            1127
#define IDC_STATIC_ALTNEUOBERFL         1128
#define IDC_STATIC_MASSE_NEU            1128
#define IDC_STATIC_ALTNEUFEHLER         1129
#define IDC_COMBO_BISSTEINNUMMERN       1129
#define IDC_STATIC_OBERFLAEHE_AE        1130
#define IDC_STATIC_BESTELLEINGANG       1131
#define IDC_STATIC_DICKETEXT            1132
#define IDC_STATIC_BREITETEXT           1133
#define IDC_STATIC_LAENGETEXT           1134
#define IDC_STATIC_LBD                  1135
#define IDC_STATIC_MATERIALTEXT         1136
#define IDC_COMBO_LAGER1                1137
#define IDC_LIST_BESTELLEINGANG         1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
